services:
  explorer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3007:3005"
    environment:
      FIRST_CONNECTION_TOKEN: ${FIRST_CONNECTION_TOKEN}
      AUTH_SECRET: ${AUTH_SECRET}
    volumes:
      - ./docker-data2:/app/data

  # explorer:
  #   image: ghcr.io/ledouxm/kysely-explorer:latest
  #   ports:
  #     - "3006:3005"
  #   environment:
  #     FIRST_CONNECTION_TOKEN: ${FIRST_CONNECTION_TOKEN}
  #     AUTH_SECRET: ${AUTH_SECRET}
  #   volumes:
  #     - ./docker-data:/app/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user_xyz789
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: testdb
    # ports:
    #   - "49152:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_xyz789 -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
      MYSQL_USER: mysql_user_abc123
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_DATABASE: testdb
    # ports:
    #   - "49153:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "mysql_user_abc123",
          "-p mysqlpassword",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: MSSQLpassword0
      MSSQL_PID: Developer
    # ports:
    #   - "49154:1433"
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "MSSQLpassword0",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Note: Turso is typically used as an edge database and doesn't have an official Docker image
  # This is using libsql which is the open source database that powers Turso
  turso:
    image: ghcr.io/tursodatabase/libsql-server:latest
    environment:
      ADMIN_TOKEN: tursopassword
    # ports:
    #   - "49155:8080"
    command: ["--http-port", "8080", "--auth-token", "tursopassword"]
# postgresql://user_xyz789:postgrespassword@postgres/testdb
# mysql://mysql_user_abc123:mysqlpassword@mysql/testdb
# Server=mssql,1433;Database=master;User Id=sa;Password=MSSQLpassword0;TrustServerCertificate=True
# http://turso:8080?auth_token=tursopassword
