name: Create and publish a Docker image

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if version already exists
        id: version-check
        run: |
          VERSION=${{ steps.package-version.outputs.version }}
          IMAGE_URL="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"

          if docker manifest inspect "${IMAGE_URL}" > /dev/null 2>&1; then
            echo "❌ Version ${VERSION} already exists in the registry!"
            echo "Please update the version in package.json before pushing."
            exit 1
          else
            echo "✅ Version ${VERSION} does not exist. Proceeding with build..."
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.package-version.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
